//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaseHome.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Gender = 0;
            this.DelFlag = 0;
            this.LoginErrorTimes = 0;
        }
    
        public int AccountId { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string PhoneNum { get; set; }
        public Nullable<byte> Gender { get; set; }
        public System.DateTime RegTime { get; set; }
        public byte DelFlag { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<byte> LoginErrorTimes { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
